In [21]:
import numpy as np
from sklearn import preprocessing

Дан числовой признак, и требуется разбить его на дискретные корзины.

In [22]:
age = np.array([
    [6],
    [12],
    [20],
    [36],
    [65]
])

# Creating the binarizer
binarizer = preprocessing.Binarizer(threshold=18)

# Transform the feature
binarizer.fit_transform(age)  # = np.digitize(age, bins=[18])

array([[0],
       [0],
       [1],
       [1],
       [1]])

In [23]:
np.digitize(age, bins=[20, 30, 64])

array([[0],
       [0],
       [1],
       [2],
       [3]])

In [24]:
np.digitize(age, bins=[20, 30, 64], right=True)

array([[0],
       [0],
       [0],
       [2],
       [3]])