In [18]:
import numpy as np
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

Finding eigen values and eigen vectors.  
В интуитивном плане, имея линейное преобразование, представленное матрицей А,
можно сказать, что ***собственные векторы*** — это векторы, которые при применении
этого преобразования изменяются **только в масштабе** (а не в направлении).  
Более формально: $Av = lv$  
где $А$ — это квадратная матрица; $l$ — собственное значение; $v$ — собственный вектор.

In [19]:
eigenvalues, eigenvector = np.linalg.eig(matrix)
print(eigenvalues)
print()
print(eigenvector)

[13.55075847  0.74003145 -3.29078992]

[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]
11


In [ ]:
print(matrix.trace())
print(

In [20]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

#### Scalar multiplication <-> dot product  
#### $\sum_{i=1}^n a_ib_i$

In [21]:
np.dot(vector_a, vector_b)  # vector_a @ vector_b

32

Adding and subtracting matrices

In [22]:
matrix_a = np.array([
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]
])

matrix_b = np.array([
    [3, 3, 3],
    [2, 2, 2],
    [1, 1, 1]
])

In [23]:
np.add(matrix_a, matrix_b)  # a + b
np.subtract(matrix_a, matrix_b)  # a - b

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

Matrix multiplication

In [24]:
np.dot(matrix_a, matrix_b)  # a @ b

array([[ 6,  6,  6],
       [12, 12, 12],
       [18, 18, 18]])

For element-wise multiplication

In [25]:
matrix_a * matrix_b

array([[3, 3, 3],
       [4, 4, 4],
       [3, 3, 3]])

In [26]:
matrix = np.array([
    [1, 4],
    [2, 5]
])

#### Find inverse matrix $AA^{-1} = I$

In [27]:
np.linalg.inv(matrix)
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

#### To set start value for the random numbers generator

In [28]:
np.random.seed(0)

In [29]:
# To generate random numbers
np.random.random(3)
np.random.randint(0, 11, 3)

array([3, 7, 9])

Extract 3 random numbers from normal distribution with average = 0 and standard deviation = 1

In [30]:
np.random.normal(0, 1, 3)

array([-1.42232584,  1.52006949, -0.29139398])

Extract 3 random numbers from logistic distribution with average = 0 and scale = 1

In [31]:
np.random.logistic(0, 1, 3)

array([-0.98118713, -0.08939902,  1.46416405])

Extract 3 random numbers that are bigger or equal 1 and less 2

In [32]:
np.random.uniform(1, 2, 3)

array([1.47997717, 1.3927848 , 1.83607876])