In [46]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

Flatten a matrix? i.e. transform to a 1D array

In [47]:
matrix.flatten()  # matrix.reshape(1, -1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Finding a matrix rank - dimensions of the vector space that are covered by its cols and rows

In [48]:
np.linalg.matrix_rank(matrix)

2

Finding a matrix determinant - a scalar quantity that characterizes the oriented ***"stretching"***
or ***"compression"*** of a multidimensional Euclidean space after transformation by a matrix.
**Makes sense only for square matrices.**

In [49]:
np.linalg.det(matrix)

0.0

In [50]:
matrix.diagonal()

array([1, 5, 9])

In [51]:
matrix.diagonal(offset=1)

array([2, 6])

In [52]:
matrix.diagonal(offset=-1)

array([4, 8])

Trace of a matrix - sum of the main diagonal elements

In [53]:
matrix.trace()

15