In [71]:
import numpy as np

In [72]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [73]:
add_100 = lambda i: i + 100

**Creating vectorized function**

In [74]:
vectorized_add_100 = np.vectorize(add_100)  # works as the "for-loop" so it doesn't increase efficiency

Apply the function to each element of the matrix

In [75]:
vectorized_add_100(matrix)  # like matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [76]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [77]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
print(np.max(matrix, axis=0)) # find max element in every COLUMN

[7 8 9]


In [79]:
print(np.max(matrix, axis=1)) # find max element in every ROW

[3 6 9]


In [80]:
# Average
print(np.mean(matrix, axis=0))  # np.average

print(np.mean(matrix, axis=1)) 

print(np.mean(matrix))

# Variance
print(np.var(matrix))

# Standard deviation
print(np.std(matrix))

[4. 5. 6.]
[2. 5. 8.]
5.0
6.666666666666667
2.581988897471611


In [81]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

Formatting 3x4 matrix to 6x2

In [82]:
print(matrix.reshape(6, 2))  # 
                             # 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [83]:
print(matrix.reshape(1, -1)) # = print(matrix.reshape(12))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


-1 as argument means **"as much as necessary"**
if give size of matrix it returns 1D array

In [84]:
print(matrix.reshape(-1, 1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


Transpose a matrix

In [85]:
matrix.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Transpose a vector

In [86]:
vector = np.array([1, 2, 3, 4, 5])
vector.T

array([1, 2, 3, 4, 5])

vector-row to vector-col <-> transposed vector

In [87]:
vector = np.array([[1, 2, 3, 4, 5]]) # doubled []
vector.T

array([[1],
       [2],
       [3],
       [4],
       [5]])