In [8]:
import numpy as np
from scipy import sparse

In [9]:
# vector as a row
vector_row = np.array([1, 2, 3])
vector_row

array([1, 2, 3])

In [10]:
# vector as column
vector_column = np.array([
    [1],
    [2],
    [3]
])
vector_column

array([[1],
       [2],
       [3]])

In [11]:
# matrix
matrix = np.array([
    [0, 0],
    [0, 1],
    [3, 0]
])
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

***(Compressed Sparse Row) CSR-matrix.*** The matrix stores only non-zero values - for computing economy

In [12]:
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [13]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Number of rows and columns
print(matrix.shape)

# Row * Column
print(matrix.size)

# Number of dimensions
print(matrix.ndim)


(3, 4)
12
2
